[package]
name = "data-transfer-api"
version = "0.1.0"
authors = ["Daniel"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fs2 = "0.4.3"
boolinator = "2.4.0"